version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_container
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:80"
        working_dir: /var/www/html
        restart: always
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: database_container
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        volumes:
            - database:/var/lib/mysql
volumes:
    database:
